name: salmonn2
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.5.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - pip
  - pip:
      - transformers==4.38.2
      - accelerate==0.27.2
      - peft==0.8.2
      - bitsandbytes>=0.42.0
      - datasets
      - librosa
      - soundfile
      - scipy
      - omegaconf
      - fire
      - sentencepiece
      - tqdm
      - scikit-learn
      - pyyaml
      - pandas