name: salmonn_new
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
      - transformers==4.28.0
      - accelerate==0.20.3
      - peft==0.3.0
      - bitsandbytes==0.41.1
      - sentencepiece==0.1.97
      - omegaconf==2.3.0
      - librosa==0.11.0
      - soundfile==0.12.1
      - scipy==1.13.1
      - datasets==3.3.2
      - fire
      - tqdm