"""
Symbol Manager for dynamic/fixed symbol handling and optional label swapping.
"""

import json
import logging
import os
import random
import re
import string
from typing import Any, Dict, List, Optional, Tuple
from transformers import PreTrainedTokenizer

from config.data_config.master_config import DATASET_CONFIGS

# Default path for precomputed H2 scores (generated by analysis/score_vocab.py)
_DEFAULT_SCORES_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "analysis", "vocab_h2_scores.json",
)
_SCORED_POOL_CACHE: Optional[Dict] = None  # module-level cache, loaded once


def _load_scored_pool(path: str = _DEFAULT_SCORES_PATH) -> Optional[Dict]:
    """Load vocab_h2_scores.json once and cache it."""
    global _SCORED_POOL_CACHE
    if _SCORED_POOL_CACHE is not None:
        return _SCORED_POOL_CACHE
    if not os.path.exists(path):
        logging.warning("vocab_h2_scores.json not found at %s — difficulty filter disabled", path)
        return None
    with open(path) as f:
        data = json.load(f)
    _SCORED_POOL_CACHE = data
    logging.info(
        "Loaded vocab_h2_scores: hard_pool=%d, easy_pool=%d (first-token deduplicated)",
        len(data.get("hard_pool", [])), len(data.get("easy_pool", [])),
    )
    return _SCORED_POOL_CACHE


def _get_difficulty_pool(difficulty: str, scores: Dict) -> List[str]:
    """Return the deduplicated symbol list for the requested difficulty tier.

    Uses pre-built hard_pool / easy_pool keys (one symbol per unique first BPE token)
    to avoid first-token collisions between label symbols during training.
    Falls back to threshold filtering if the keys are absent (legacy json).
    """
    if difficulty == "easy" and "easy_pool" in scores:
        return list(scores["easy_pool"])
    if difficulty == "hard" and "hard_pool" in scores:
        return list(scores["hard_pool"])
    # legacy fallback: re-filter by thresholds (no dedup)
    thresholds = scores["meta"]["thresholds"]
    safe = {s: v for s, v in scores["symbols"].items() if not v["h4_risk"]}
    if difficulty == "easy":
        return [s for s, v in safe.items() if v["lp_total"] >= thresholds["easy_lp_total_min"]]
    if difficulty == "hard":
        return [s for s, v in safe.items() if v["lp_total"] <= thresholds["hard_lp_total_max"]]
    return list(safe.keys())  # "random" — all safe symbols


def generate_fresh_symbols(
    tokenizer: "PreTrainedTokenizer",
    num_symbols: int,
    token_size: int = 2,
) -> List[str]:
    """
    Generate random lowercase strings that tokenize to exactly `token_size` tokens
    and remain atomic when adjacent to punctuation (comma checks).

    Works for any token_size: standalone len == token_size, "word," len == token_size+1
    with first token_size IDs matching, and ", word" len == token_size+1.
    """
    words, used, attempts = [], set(), 0
    while len(words) < num_symbols and attempts < 100_000:
        attempts += 1
        w = "".join(random.choice(string.ascii_lowercase) for _ in range(random.choice([4, 5])))
        if w in used:
            continue
        used.add(w)
        try:
            w_ids = tokenizer.encode(w, add_special_tokens=False)
            if len(w_ids) != token_size:
                continue
            w_comma_ids = tokenizer.encode(f"{w},", add_special_tokens=False)
            cs_w_ids = tokenizer.encode(f", {w}", add_special_tokens=False)
            if not (
                len(w_comma_ids) == token_size + 1
                and w_comma_ids[:token_size] == w_ids
                and len(cs_w_ids) == token_size + 1
            ):
                continue
            words.append(w)
        except Exception:
            continue
    if len(words) < num_symbols:
        logging.warning(
            "generate_fresh_symbols: only generated %d/%d symbols (token_size=%d)",
            len(words), num_symbols, token_size,
        )
    return words[:num_symbols]


def get_dataset_info(batch: Dict, fallback_labels: Optional[List[str]] = None) -> Tuple[str, List[str]]:
    """Extract dataset name string and sorted label list from a batch."""
    ds = batch.get("dataset_type", [])
    ds = ds[0] if isinstance(ds, list) and ds else ds
    ds_name_str = ds.value if hasattr(ds, "value") else str(ds)
    for dt_enum, ds_cfg in DATASET_CONFIGS.items():
        if dt_enum.value == ds_name_str:
            return ds_name_str, sorted(list(ds_cfg.valid_labels))
    return ds_name_str, (fallback_labels or [])


def compute_slot_offsets(training_ds_names: set) -> Dict[str, int]:
    """Return {ds_name: slot_offset} for each training dataset, sorted alphabetically.
    Guarantees non-overlapping slot ranges across datasets."""
    offsets, offset = {}, 0
    for dt_enum, ds_cfg in sorted(DATASET_CONFIGS.items(), key=lambda x: x[0].value):
        if dt_enum.value in training_ds_names:
            offsets[dt_enum.value] = offset
            offset += len(ds_cfg.valid_labels)
    return offsets


def tokenize_batch_with_audio(batch: Dict, processor, completions, padding_side: str = "right") -> Dict:
    """Inject precomputed audio into prompt dicts then tokenize. Shared by training and validation."""
    if processor is None or "prompt" not in batch:
        return batch
    if batch.get("audio"):
        precomp_list = batch.get("_precomputed", [None] * len(batch["prompt"]))
        for p, a, pre in zip(batch["prompt"], batch["audio"], precomp_list):
            if isinstance(p, dict):
                p["_audio"] = a
                if pre is not None:
                    p["_precomputed"] = pre
    tokenized_data = processor.tokenize_batch(batch["prompt"], completions=completions, padding_side=padding_side)
    batch.update(tokenized_data)
    return batch


class SymbolManager:
    """Manages mappings used to rewrite labels in prompt/completion text."""

    def __init__(
        self,
        original_labels: List[str],
        tokenizer: PreTrainedTokenizer,
        dynamic_per_epoch: bool = False,
        token_size: int = 2,
        no_symbols: bool = False,
        swap_labels: bool = False,
        labels_per_dataset: Optional[Dict[str, List[str]]] = None,
        symbol_difficulty: str = "random",
        val_symbol_difficulty: str = "easy",
        num_symbol_mappings: int = 20,
    ):
        self.original_labels = sorted(list(set(original_labels)))
        self.labels_per_dataset: Dict[str, List[str]] = labels_per_dataset or {}
        self.tokenizer = tokenizer
        self.dynamic_per_epoch = dynamic_per_epoch
        self.token_size = token_size
        self.no_symbols = no_symbols
        self.swap_labels = swap_labels
        self.symbol_difficulty = symbol_difficulty
        self.val_symbol_difficulty = val_symbol_difficulty
        self.num_symbol_mappings = num_symbol_mappings

        # Load H2 scored pool once if any difficulty filter is active
        self._scored_pool_data: Optional[Dict] = None
        if symbol_difficulty != "random" or val_symbol_difficulty != "random":
            self._scored_pool_data = _load_scored_pool()

        # Pre-generate M mappings upfront for dynamic modes (per_epoch / per_instance).
        # Avoids tokenizer calls during training; both modes draw from this pool.
        self._pregenerated_mappings: List[Dict[str, Dict[str, str]]] = []

        # Per-dataset symbol mappings: {ds_name: {label: symbol}}
        # Each dataset gets independently generated symbols so overlapping labels
        # (e.g. "neutral" in meld_emotion AND voxceleb) map to different symbols.
        self.fixed_mappings: Dict[str, Dict[str, str]] = {}
        self.epoch_mappings_history: Dict[int, Dict[str, Dict[str, str]]] = {}
        self.current_epoch = 0

        self._pure_symbol_mappings: Dict[str, Dict[str, str]] = {}
        if not self.no_symbols:
            self._pure_symbol_mappings = self._generate_per_ds_symbols()

        if self.no_symbols and not self.swap_labels:
            logging.info("No-symbol mode enabled - symbol replacement is disabled")
        elif self.swap_labels:
            logging.info("Swap mode enabled (update_strategy controls per-epoch vs per-instance)")
            if self._pure_symbol_mappings:
                logging.info("Base symbol pool for swap: %s", self._pure_symbol_mappings)
        elif not self.dynamic_per_epoch:
            self.fixed_mappings = {ds: dict(m) for ds, m in self._pure_symbol_mappings.items()}
            logging.info("Generated fixed mappings: %s", self.fixed_mappings)
        else:
            # Pre-generate M mappings at init — avoids tokenizer calls during training.
            # Per epoch: pool[epoch % M]. Per instance: random.choice(pool).
            logging.info(
                "Dynamic mode: pre-generating %d symbol mappings (difficulty=%s) ...",
                self.num_symbol_mappings, self.symbol_difficulty,
            )
            self._pregenerated_mappings = [
                self._generate_per_ds_symbols(self.symbol_difficulty)
                for _ in range(self.num_symbol_mappings)
            ]
            logging.info(
                "Pre-generated %d mappings. Example mapping[0]: %s",
                len(self._pregenerated_mappings),
                {ds: list(m.items())[:2] for ds, m in self._pregenerated_mappings[0].items()},
            )

    def get_symbols_for_epoch(self, epoch: int, force_new_symbols: bool = False) -> Dict[str, Dict[str, str]]:
        """Return {ds_name: {label: symbol}} for all datasets.

        Dynamic modes draw from the pre-generated pool:
          per_epoch   (force_new=False): pool[epoch % M] — same map for the whole epoch
          per_instance (force_new=True): random.choice(pool) — different every batch
        """
        if self.no_symbols and not self.swap_labels: return {}
        if not self.dynamic_per_epoch: return self.fixed_mappings

        if self._pregenerated_mappings:
            if force_new_symbols:
                # per_instance: random pick each call
                return random.choice(self._pregenerated_mappings)
            else:
                # per_epoch: deterministic slot, changes each epoch, no repeats up to M epochs
                idx = epoch % len(self._pregenerated_mappings)
                self.current_epoch = epoch
                return self._pregenerated_mappings[idx]

        # Fallback: generate on the fly (old behaviour, no scored pool loaded)
        if force_new_symbols or epoch not in self.epoch_mappings_history:
            self.epoch_mappings_history[epoch] = self._generate_symbol_mappings()
        self.current_epoch = epoch
        return self.epoch_mappings_history[epoch]

    def get_flat_symbols_for_ds(self, ds_name: str, epoch: Optional[int] = None) -> Dict[str, str]:
        """Return flat {label: symbol} for a single dataset.
        Falls back to the "" key for backward compat when labels_per_dataset was not set."""
        per_ds = self.get_symbols_for_epoch(epoch) if epoch is not None else self.fixed_mappings
        return dict(per_ds.get(ds_name) or per_ds.get("") or {})

    def get_current_symbols(self) -> Dict[str, Dict[str, str]]:
        if not self.dynamic_per_epoch: return self.fixed_mappings
        return self.epoch_mappings_history.get(self.current_epoch, {})

    def get_reverse_mappings(self, epoch: Optional[int] = None, mappings: Optional[Dict[str, str]] = None) -> Dict[str, str]:
        """Reverse a flat {label: symbol} mapping. Pass mappings= explicitly; epoch is ignored (per-dataset maps cannot be auto-flattened)."""
        active = mappings or {}
        return {v.lower(): k for k, v in active.items()}

    def _generate_per_ds_symbols(self, difficulty: str = "random") -> Dict[str, Dict[str, str]]:
        """Generate globally unique symbols across all datasets, then slice per dataset."""
        result = {}
        if self.labels_per_dataset:
            ds_items = sorted(self.labels_per_dataset.items())
            total = sum(len(labels) for _, labels in ds_items)
            all_syms = self._generate_two_token_symbols(total, self.token_size, difficulty)
            offset = 0
            for ds_name, labels in ds_items:
                n = len(labels)
                result[ds_name] = dict(zip(labels, all_syms[offset:offset + n]))
                offset += n
        else:
            syms = self._generate_two_token_symbols(len(self.original_labels), self.token_size, difficulty)
            result[""] = dict(zip(self.original_labels, syms))
        return result

    def _generate_symbol_mappings(self, force: bool = False,
                                  difficulty: Optional[str] = None) -> Dict[str, Dict[str, str]]:
        if self.no_symbols and not force: return {}
        return self._generate_per_ds_symbols(difficulty or self.symbol_difficulty)

    def generate_swap_mapping_for_labels(
        self,
        relevant_labels: List[str],
        base_symbol_mapping: Optional[Dict[str, str]] = None,
        epoch: Optional[int] = None,
    ) -> Dict[str, str]:
        """
        Generate a swap mapping scoped to the given dataset's label set.

        base_symbol_mapping: if provided (self.no_symbols=False), shuffles symbols across
                             labels (swap at symbol level). If None (self.no_symbols=True),
                             shuffles the original label names within this set.
        epoch: if provided (per_epoch mode), seeds the shuffle from (epoch, labels) so
               the same epoch always produces the same mapping. If None (per_instance
               mode), uses global random state for batch-level variety.
        """
        labels = sorted(list(set(relevant_labels)))
        if len(labels) <= 1:
            return {l: l for l in labels}

        if epoch is not None:
            rng = random.Random(hash((epoch, tuple(labels))) & 0x7FFFFFFF)
            shuffle_fn = rng.shuffle
        else:
            shuffle_fn = random.shuffle

        if self.no_symbols or not base_symbol_mapping:
            shuffled = labels[:]
            shuffle_fn(shuffled)
            return dict(zip(labels, shuffled))
        else:
            symbols = [base_symbol_mapping.get(l, l) for l in labels]
            shuffle_fn(symbols)
            return dict(zip(labels, symbols))

    def _generate_two_token_symbols(self, num_symbols: int, token_size: int = 2,
                                    difficulty: str = "random") -> List[str]:
        if difficulty != "random" and self._scored_pool_data:
            pool = _get_difficulty_pool(difficulty, self._scored_pool_data)
            if len(pool) >= num_symbols:
                chosen = random.sample(pool, num_symbols)
                logging.info(
                    "Symbol generation: difficulty=%s  requested=%d  pool=%d  sampled=%s",
                    difficulty, num_symbols, len(pool), chosen,
                )
                return chosen
            logging.warning(
                "difficulty=%s pool too small (%d < %d), falling back to random",
                difficulty, len(pool), num_symbols,
            )
        return generate_fresh_symbols(self.tokenizer, num_symbols, token_size)

    def _apply_mapping_safe(self, text: str, mapping: Dict[str, str]) -> str:
        if not mapping: return text

        # Protect description text in bullet lines from label replacement.
        # "- label: DESCRIPTION" — DESCRIPTION may contain the label word as a regular
        # English word (e.g. "other: Actions that don't fit other categories") and
        # must not be replaced. Only the label name (before the colon) is a target.
        desc_store = {}
        def _protect_desc(m):
            key = f"__DESCPROTECT_{len(desc_store):04d}__"
            desc_store[key] = m.group(2)
            return m.group(1) + key
        protected = re.sub(r'(?m)^([ \t]*-[^:\n]+: )(.+)$', _protect_desc, text)

        placeholders, transformed = {}, protected
        sorted_keys = sorted(mapping.keys(), key=len, reverse=True)
        for idx, src in enumerate(sorted_keys):
            placeholder = f"__SWAP_PLACEHOLDER_{idx}__"
            placeholders[placeholder] = mapping[src]
            transformed = re.compile(r'\b' + re.escape(src) + r'\b', re.IGNORECASE).sub(placeholder, transformed)
        for p, d in placeholders.items():
            transformed = transformed.replace(p, d)

        for key, val in desc_store.items():
            transformed = transformed.replace(key, val)
        return transformed

    def _apply_mapping_to_prompt_obj(self, prompt_obj: Any, mapping: Dict[str, str]) -> Any:
        if isinstance(prompt_obj, str): return self._apply_mapping_safe(prompt_obj, mapping)
        if isinstance(prompt_obj, dict) and "conversation" in prompt_obj:
            new_obj = dict(prompt_obj)
            new_conv = []
            for msg in prompt_obj.get("conversation", []):
                new_msg = dict(msg)
                if isinstance(new_msg.get("content"), str): new_msg["content"] = self._apply_mapping_safe(new_msg["content"], mapping)
                elif isinstance(new_msg.get("content"), list):
                    new_msg["content"] = [{"type": p["type"], "text": self._apply_mapping_safe(p["text"], mapping)} if p.get("type") == "text" else p for p in new_msg["content"]]
                new_conv.append(new_msg)
            new_obj["conversation"] = new_conv
            return new_obj
        return prompt_obj

    def replace_symbols_in_batch(self, batch, prompt_mappings, completion_mappings=None):
        p_map = prompt_mappings
        c_map = completion_mappings or prompt_mappings
        if not p_map: return batch
        updated = batch.copy()
        if "prompt" in batch: updated["prompt"] = [self._apply_mapping_to_prompt_obj(p, p_map) for p in batch["prompt"]]
        if "completion" in batch: updated["completion"] = [self._apply_mapping_safe(c, c_map) for c in batch["completion"]]
        return updated

    def convert_symbols_back(self, text: str, epoch: Optional[int] = None, mappings: Optional[Dict[str, str]] = None) -> str:
        if mappings is None and epoch is None and self.no_symbols and not self.swap_labels: return text
        rev = self.get_reverse_mappings(epoch=epoch, mappings=mappings)
        for s, l in rev.items():
            if s in text.lower(): text = re.compile(re.escape(s), re.IGNORECASE).sub(l, text)
        return text
