name: salmonn2
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=12.1
  # - aiodns=3.1.1
  # - aiohappyeyeballs=0.4.0
  # - aiohttp=3.9.1
  # - aiosignal=1.3.1
  # - attrs=23.2.0
  - blas
  - bottleneck
  - brotlicffi
  - bzip2
  - c-ares=1.24.0
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - cmake
  - datasets=2.14.6
  - dill
  - expat
  - ffmpeg
  - filelock
  - freetype
  - fribidi
  # - frozenlist
  - gmp
  - gmpy2
  - icu
  - idna
  - intel-openmp
  - jinja2
  - jpeg
  - lame
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libglib
  - libgomp
  - libiconv
  - libpng
  - libprotobuf
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxml2
  - libzlib
  - lz4-c
  - markupsafe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - mpc
  - mpfr
  - mpmath
  # - multidict
  - multiprocess
  - ncurses
  - networkx
  - numexpr
  - numpy
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  # - pycares=4.4.0
  - pycparser
  - pysocks
  - python-dateutil
  - python-tzdata
  # - python-xxhash
  - pytz
  - pyyaml
  - readline
  - requests
  - setuptools
  - six
  - snappy
  - sqlite
  - sympy
  - tk
  - tqdm
  - typing-extensions
  - tzdata
  - urllib3
  - wheel
  - xz
  - yaml
  # - yarl
  - zlib
  - zstd
  - pip:
      - accelerate==0.20.3
      - antlr4-python3-runtime==4.9.3
      - audioread==3.1.0
      - bitsandbytes==0.45.0
      - decorator==5.2.1
      - fire==0.7.1
      - fsspec==2023.9.0
      - hf-xet==1.1.10
      - huggingface-hub==0.35.0
      - joblib==1.5.2
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite
      - msgpack==1.1.2
      - numba
      - omegaconf==2.3.0
      - peft==0.3.0
      - platformdirs==4.4.0
      - pooch==1.8.2
      - psutil==7.1.0
      - python-dotenv==1.0.0
      - regex==2025.9.1
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - sentencepiece==0.1.97
      - soundfile==0.12.1
      - soxr==1.0.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.13.3
      - transformers==4.28.0
      - aiodns==3.1.1
      - aiohappyeyeballs==0.4.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - attrs==23.2.0
      - frozenlist
      - multidict
      - pycares==4.4.0
      - xxhash
      - yarl
